services:
  db:
    image: mysql:9.0
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: sauna-tankentai
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true #擬似端末をコンテナに結びつける
    stdin_open: true  #標準入出力とエラー出力をコンテナに結びつける
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:  #myappに反映する
      - .:/myapp
volumes:
  mysql_data: